name: Publish on GitHub Pages

on:
  push:
    branches:
      - main
      - 'dev/**'
  schedule:
    - cron: '5 2 * * *'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Deno environment
        uses: denolib/setup-deno@v2
        with:
          deno-version: '1.x'

      - name: Build site
        run: deno task build
      
      - name: Setup Pages
        uses: actions/configure-pages@v2
      
      - name: Upload artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      # Adding this because schedule workflows may stop if there's a 60-day gap between repo activity
      - name: Write Schedule Log
        run: echo "Deployed at $(date)\n" >> schedule.log
        if: github.event_name == 'schedule'

      - name: Commit Schedule Log
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: Update schedule deploy log `date`"
          add: "schedule.log"
          committer_name: "GitHub Actions"
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
        if: github.event_name == 'schedule'
  
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        # if: github.ref == 'refs/heads/main'